### ISSUE TITLE
Catchup + proxy reverse 

### ISSUE THREAD

**Issue by SanderM2** [euzu/m3u-filter#82]
If m3u-filter is set up for reverse proxy, you can use the catchup service to play a program from the past, but you won't be able to rewind or fast-forward within that program. However, when it is configured as a redirect, these features do work.

There is nothing in the logs while rewinding or fast-forwarding.

**Comment by euzu** [comment]
The difference between reverse and redirect  is
redirect -> the api from the original provider is used and stream comes from the provider to the client
reverse -> the api from m3u-filter is used and the stream goes through m3u-filter to the client

This means the api is not implemented fully in m3u-filter, i need to know what api the client is calling i reverse proxy mode. I think the client gets 404 as response because of unknown api call.

**Comment by euzu** [comment]
i think this is the same as [catchup](https://github.com/euzu/m3u-filter/issues/78)

**Comment by pletexier** [comment]
Hi @euzu,

Seeking in a film is not working in Reverse proxy mode.
I think this is the same problem as catchup here.

Regards,

Patrice
